### ISSUE TITLE
return zero function addAllIHaveCustomMappings  ---profiles

### ISSUE THREAD

**Issue by amir3164** [VahidN/AutoMapperSamples#2]
<div dir="rtl">

سلام اقای نصیری
دلیل اینکه تابع addAllIHaveCustomMappings   خط 
</div>

```csharp
  var profiles = ctx.GetAllInstances<IHaveCustomMappings>().ToList();
```
مقدار صفر بر میگردد چیه؟ 
IHaveCustomMappings   مدل های که از 
    استفاده کرده رو شناسایی نمی کند؟نمیدونم چرا شناسایی نمیکند.ممنون

**Comment by VahidN** [comment]
<div dir="rtl">

[اين سطر](https://github.com/VahidN/AutoMapperSamples/blob/master/Sample03/IoCConfig/AutomapperRegistry.cs#L19) هست كه كار اسكن اين نوع‌ها را انجام مي‌دهد
</div>

```csharp
scan.AddAllTypesOf<IHaveCustomMappings>().NameBy(item => item.FullName);
```
<div dir="rtl">

اگر اين نوع‌ها در اسمبلي ديگري هستند بايد آن اسمبلي را هم [فعال كنيد](https://github.com/VahidN/AutoMapperSamples/blob/master/Sample03/IoCConfig/AutomapperRegistry.cs#L15):
</div>

```csharp
scan.AssemblyContainingType<SomeTypeInThatAsm>(); // for other asms, if any.
```

**Comment by amir3164** [comment]
ممنون اقای نصیری مشکلم 
scan.AssemblyContainingType<'SomeTypeInThatAsm'>(); 
این قسمت بود من  لایه مدلم جدا بود امدم اینکار رو انجام دادم  مشکل حل شد.
  scan.AssemblyContainingType<'UserVModel'>();
فقط یه سوال؟ ایا من برای هر  ویو مدلم باید بیایم اضافه کنم
مثلا اگه مدل   
ApplicationUserViewModel 
باید اضافه کنم؟

**Comment by VahidN** [comment]
<div dir="rtl">
خير. ذكر يك مورد براي علامتگذاري كل اسمبلي كافي هست
