### ISSUE TITLE
بهترین روش استفاده automaper  

### ISSUE THREAD

**Issue by amir3164** [VahidN/AutoMapperSamples#3]
با سلام
automaper زمانی که 
 رو در لایه سرویس استفاده پیاده سازی  کردیم  بهترین روش استفاده ان در لایه سرویس برنامه هست 
یا در  داخل
 Controllers
برنامه استفاده کنیم
چون بعضی از 
open sourceها
 امدن داخل 
 Controllersmap
کردن و بعضی ها د داخل لایه سرویس مربوطه

 _mapper.Map(source: user, destination: viewuser);

با تشکر

**Comment by VahidN** [comment]
[follow this article and its comments](http://www.dotnettips.info/courses/topic/16/65199451-6991-4426-81ab-97daba8bb5a8)
